version: '3.8'
services:
  postgres:
    image: postgres:15
    container_name: fitness-postgres
    environment:
      POSTGRES_DB: fitness-user-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - fitness-network

  mongodb:
    image: mongo:7
    container_name: fitness-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - fitness-network

volumes:
  postgres_data:
  mongodb_data:

networks:
  fitness-network:
    driver: bridge
